const egPrompts = [
  "Create a modern login form with email and password fields",
  "Design a signup page with social login buttons",
  "Build a responsive navbar with dropdown menu",
  "Create a pricing card with 3 plans",
  "Design a dashboard with sidebar and charts",
  "Build a profile card with avatar and bio",
  "Create a settings page with toggle switches",
  "Design a product card with image and add to cart button",
  "Build a chat UI with message bubbles",
  "Create a landing page hero section with CTA",
  "Design a contact form with validation",
  "Build a table with sorting and pagination",
  "Create a notification toast component",
  "Design a modal popup with overlay",
  "Build a sidebar navigation with icons",
  "Create a search bar with autocomplete",
  "Design a blog post card layout",
  "Build a file upload component with drag and drop",
  "Create a calendar UI component",
  "Design a testimonial slider",
  "Build a music player UI",
  "Create a dark mode toggle switch",
  "Design a multi-step form wizard",
  "Build a breadcrumb navigation",
  "Create a loading spinner animation",
  "Design an FAQ accordion component",
  "Build a user list with avatars and actions",
  "Create a dropdown select menu",
  "Design a stats card with graphs",
  "Build a mobile bottom navigation bar",
  "Create a wishlist/favorites UI",
  "Design a checkout page layout",
  "Build a rating component with stars",
  "Create a timeline component",
  "Design a Kanban board UI",
  "Build a weather widget UI",
  "Create a sidebar with collapsible sections",
  "Design a newsletter subscription form",
  "Build a video player UI",
  "Create a comments section with replies",
  "Design a portfolio grid layout",
  "Build an e-commerce product detail page",
  "Create a badge and tag component",
  "Design a login page with illustration",
  "Build a map UI with location markers",
  "Create a task manager UI with checkboxes",
  "Design a popup notification center",
  "Build a responsive image gallery",
  "Create a progress bar component",
  "Design a simple calculator UI"
]

export const getRandomPrompts = (n: number) => {
  //creating a copy doesn't mutating original array
  const suffled = [...egPrompts].sort(() => 0.5 - Math.random());
  return suffled.slice(0, n);
}

